/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.command.CsvTool;

import picocli.CommandLine;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        int exitCode = new CommandLine(new CsvTool()).execute(args);
        System.exit(exitCode);
    }
}
